sudo: required

services:
  - docker

before_install:
  - docker build -t aww-umbrage/symmetrical-succotash -f Dockerfile.dev .

script:
  - docker run -e CI=true aww-umbrage/symmetrical-succotash npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "EB-practice"
  env: "EB-Practice-env"
  bucket_name: "elasticbeanstalk-us-east-1-564567100372"
  bucket_path: "EB-practice"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
